firmware: Misc improvements.

diff --git a/firmware/build b/firmware/build
--- a/firmware/build
+++ b/firmware/build
@@ -10,9 +10,9 @@ COLOUR_RED='\033[0;31m'
 COLOUR_OFF='\033[0;00m'
 CLEAR_LINE='\033[2K'
 
-_ERROR_="$COLOUR_RED[ERROR]$COLOUR_OFF"
-_INFO_="$COLOUR_PURPLE[INFO]$COLOUR_OFF"
-_DEBUG_="$COLOUR_YELLOW[DEBUG]$COLOUR_OFF"
+_ERROR_="${COLOUR_RED}[ERROR]${COLOUR_OFF}"
+_INFO_="${COLOUR_PURPLE}[INFO]${COLOUR_OFF}"
+_DEBUG_="${COLOUR_YELLOW}[DEBUG]${COLOUR_OFF}"
 
 opt_flash=false
 opt_debug=false
@@ -23,35 +23,29 @@ WOLFSSL_SRC="${CHIBIOS_SRC}/ext/wolfssl"
 
 unpack_lwip () {
   if [ ! -d "${LWIP_SRC}" ]; then
-    echo "LWIP Directory not found, unpacking..";
+    printf "$_INFO_ Unpacking LwIP.. ";
     cd "${CHIBIOS_SRC}/ext/";
-    7z x lwip-*.7z;
+    7z x lwip-*.7z > /dev/null;
     if [ ! -d "${LWIP_SRC}" ]; then
-      echo "Unpacking LWIP failed! Exiting..";
+      printf "${COLOUR_RED}FAILED${COLOUR_OFF}\n";
       exit 1;
     fi
+    printf "${COLOUR_GREEN}OK${COLOUR_OFF}\n";
     cd "${source_dir}";
   fi
 }
 
 unpack_wolfssl () {
   if [ ! -d "${WOLFSSL_SRC}" ]; then
-    echo "WolfSSL Directory not found, unpacking..";
+    printf "$_INFO_ Unpacking wolfSSL.. ";
     cd "${CHIBIOS_SRC}/ext/";
-    7z x wolfssl-*.7z;
+    7z x wolfssl-*.7z > /dev/null;
     if [ ! -d "${LWIP_SRC}" ]; then
-      echo "Unpacking WolfSSL failed! Exiting..";
+      printf "${COLOUR_RED}FAILED${COLOUR_OFF}\n";
       exit 1;
     fi
+    printf "${COLOUR_GREEN}OK${COLOUR_OFF}\n";
     cd "${source_dir}";
-  fi
-}
-
-patch_lwip_time() {
-  patch -p1 -d ${CHIBIOS_SRC} -N --dry-run --silent < lwip-use-system-time.patch > /dev/null;
-  if [ $? -eq 0 ];
-  then
-    patch -p1 -d ${CHIBIOS_SRC} -N < lwip-use-system-time.patch;
   fi
 }
 
@@ -59,7 +53,15 @@ patch_lwip_dhcpretry_3s() {
   patch -p1 -d ${CHIBIOS_SRC} -N --binary --dry-run --silent < lwip-dhcpretry-3s.patch > /dev/null;
   if [ $? -eq 0 ];
   then
-    patch -p1 -d ${CHIBIOS_SRC} -N --binary < lwip-dhcpretry-3s.patch;
+    printf "$_INFO_ Patching LwIP.. ";
+    patch -p1 -d ${CHIBIOS_SRC} -N --binary --silent < lwip-dhcpretry-3s.patch;
+    if [ $? -eq 0 ];
+    then
+      printf "${COLOUR_GREEN}OK${COLOUR_OFF}\n";
+    else
+      printf "${COLOUR_RED}FAILED${COLOUR_OFF}\n";
+      exit 1;
+    fi
   fi
 }
 
@@ -100,13 +102,13 @@ size_binary() {
   size_ram=$(($size_static+$size_heap));
   size_fdata=$(($size_data+$size_rodata));
 
-  printf "==== Resources ====\n";
-  printf "RAM:       %   6s B\n" ${size_ram};
-  printf " - Static: %   6s B\n" ${size_static};
-  printf " - Heap:   %   6s B\n" ${size_heap};
-  printf "Flash:     %   6s B\n" ${size_flash};
-  printf " - Code:   %   6s B\n" ${size_text};
-  printf " - Data:   %   6s B\n" ${size_fdata};
+  printf "$_INFO_ Device Resources\n";
+  printf "  RAM:       %   6s B\n" ${size_ram};
+  printf "   - Static: %   6s B\n" ${size_static};
+  printf "   - Heap:   %   6s B\n" ${size_heap};
+  printf "  Flash:     %   6s B\n" ${size_flash};
+  printf "   - Code:   %   6s B\n" ${size_text};
+  printf "   - Data:   %   6s B\n" ${size_fdata};
 }
 
 ## Read Flags
@@ -127,28 +129,27 @@ while getopts ":DF" opt; do
 done
 for i in `seq 2 $OPTIND`; do shift; done
 
-
 unpack_lwip
 unpack_wolfssl
 
-#patch_lwip_time
 patch_lwip_dhcpretry_3s
 
 web/build
 
-#filename="$(hyphenjoin $board $program $flags `githash`)"
+filename="$(hyphenjoin "g5500" `githash`)"
 
-flags="FILE=\"${filename}\""
+flags="TARGET_FILENAME=\"${filename}\""
 
+printf "$_INFO_ Compiling..\n";
 make ${flags} \
 && {
-  #printf "$_INFO_$COLOUR_GREEN Built: ${outdir}/${filename}$COLOUR_OFF\n"
-  size_binary "builds/g5500-ethernet-controller.elf"
+  printf "$_INFO_$COLOUR_GREEN Compile OK$COLOUR_OFF\n"
+  size_binary "builds/${filename}.elf"
   if $opt_debug;
   then
-    ./debug;
+    ./debug "builds/${filename}";
   elif $opt_flash;
   then
-    ./flash;
+    ./flash "builds/${filename}";
   fi
 }
diff --git a/firmware/flash b/firmware/flash
--- a/firmware/flash
+++ b/firmware/flash
@@ -3,9 +3,19 @@
 source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
 cd "$source_dir"
 
+COLOUR_GREEN='\033[0;32m'
+COLOUR_YELLOW='\033[1;33m'
+COLOUR_PURPLE='\033[0;35m'
+COLOUR_RED='\033[0;31m'
+COLOUR_OFF='\033[0;00m'
+CLEAR_LINE='\033[2K'
+
+_ERROR_="${COLOUR_RED}[ERROR]${COLOUR_OFF}"
+_INFO_="${COLOUR_PURPLE}[INFO]${COLOUR_OFF}"
+_DEBUG_="${COLOUR_YELLOW}[DEBUG]${COLOUR_OFF}"
+
 flashtool="arm-none-eabi-gdb"
 programmer=false
-binary="builds/g5500-ethernet-controller.elf"
 
 locate_black_magic() {
   probe="`ls 2>/dev/null -Ub1 -- /dev/serial/by-id/usb-Black_Sphere_Technologies_Black_Magic_Probe_*-if00 | head -n 1`"
@@ -26,6 +36,18 @@ flash_target() {
   -ex 'load '$binary                          \
   -ex 'compare-sections';
 }
+
+binary="${1}.elf"
+
+if [ "$binary" == ".elf" ]; then
+  binary="$(ls -t builds/*.elf | head -1)"
+  echo -e "$_INFO_ Most recent build selected: ${binary}"
+fi
+
+if [[ ! -f $binary ]]; then
+  echo -e "$_ERROR_ Binary $binary not found!"
+  exit 1
+fi
 
 if programmer="`locate_black_magic`";
 then
diff --git a/firmware/web/build b/firmware/web/build
--- a/firmware/web/build
+++ b/firmware/web/build
@@ -3,17 +3,61 @@
 source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
 cd $source_dir
 
-echo "Clearing dist/ .."
+COLOUR_GREEN='\033[0;32m'
+COLOUR_YELLOW='\033[1;33m'
+COLOUR_PURPLE='\033[0;35m'
+COLOUR_RED='\033[0;31m'
+COLOUR_OFF='\033[0;00m'
+CLEAR_LINE='\033[2K'
+
+_ERROR_="${COLOUR_RED}[ERROR]${COLOUR_OFF}"
+_INFO_="${COLOUR_PURPLE}[INFO]${COLOUR_OFF}"
+_DEBUG_="${COLOUR_YELLOW}[DEBUG]${COLOUR_OFF}"
+
+opt_verbose=false
+
+printf_v() {
+	if $opt_verbose;
+	then
+		printf $1;
+	fi
+}
+printf_nv() {
+	if ! $opt_verbose;
+	then
+		printf $1;
+	fi
+}
+
+## Read Flags
+OPTIND=1
+while getopts ":v" opt; do
+  case "$opt" in
+    v) # Debug
+      opt_verbose=true
+      ;;
+    ?) # Illegal Option
+      echo -e "$_ERROR_ Illegal option '$OPTARG'"
+      exit 3
+      ;;
+  esac
+done
+for i in `seq 2 $OPTIND`; do shift; done
+
+printf "$_INFO_ Packing web files.. ";
+printf_v "\n"
+
+printf_v "Clearing dist/..\n"
 rm -fr dist/
 cp -r src/ dist/
 
-echo "Compressing files.."
+printf_v "Compressing files..\n"
 for file in $(find dist/ -type f)
 do
 	gzip -9 $file
 done
 
-echo "Packing headers.."
+printf_v "Packing headers..\n"
 for file in $(find dist/ -type f -name *.gz)
 do
 	file_path=${file%/*}
@@ -23,5 +67,6 @@ do
 	  xxd -i $file_basename > "${file_headername}"
 	  rm $file_basename
 	popd > /dev/null
-	echo "> ${file_path}/${file_headername}"
+	printf_v " - ${file_basename}\n"
 done
+printf_nv "${COLOUR_GREEN}OK${COLOUR_OFF}\n";
